export * from './utils/getFullName/getFullName.ts';
export * from './utils/declense/declense.ts';
export * from './utils/formatPhone/formatPhone.ts';
export * from './utils/getDatePeriod/getDatePeriod.ts';
export * from './utils/getUniqueItemsById/getUniqueItemsById.ts';
export * from './utils/getWeekDay/getWeekDay.ts';
export * from './utils/getZoneTime/getZoneTime.ts';
export * from './utils/isValidName/isValidName.ts';
export * from './utils/sortByName/sortByName.ts';
export * from './utils/mock/user.ts'
